version: "3.9"

services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: your_db_name
      POSTGRES_USER: your_db_user
      POSTGRES_PASSWORD: your_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - property_net

  redis:
    image: redis:latest
    container_name: property_redis
    ports:
      - "6379:6379"
    networks:
      - property_net

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    networks:
      - property_net

volumes:
  postgres_data:

networks:
  property_net:
